services:
    web:
        container_name: web
        image: nginx:alpine
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./app:/var/www/html"
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        ports:
            - "8000:80"
            - "3000:443"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
            - mysqldb
            - redis
        networks:
            - main
    php:
        container_name: php
        build:
            context: ./dockerfiles
            dockerfile: php.dockerfile
            args:
                WWW_USER_ID: ${WWW_USER_ID:-1000}
        restart: always
        tty: true
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./app:/var/www/html"
        depends_on:
            - redis
        networks:
            - main
    composer:
        container_name: composer
        image: "composer"
        volumes:
            - "./app:/app"
        command: install
    mysqldb:
        container_name: mysqldb
        image: mysql:${MYSQL_VERSION}
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "8989:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
        networks:
            - main
    redis:
        container_name: radis
        image: redis:6.2
        restart: always
        hostname: 'redis'
        ports:
            - '6379:6379'
        command: redis-server --save 20 1 --loglevel warning
        #--requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
        volumes: 
            - cache:/data
        networks:
            - main
volumes:
    dbdata6:
    cache:
        driver: local
networks:
    main:
        driver: "bridge"