name: Code analize (phpstan, rector, lint)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - name: Phpstan analizer
        run: make phpstan
      - name: rector analizer
        run: make rector
