name: Code analize (phpstan, rector, lint)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  analyze:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: symfony
          MYSQL_DATABASE: symfony_test
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    env:
      working-directory: ./app
    # concurrency:
    #   group: ${{ github.workflow }}-${{ github.ref }}
    
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          
      - uses: actions/checkout@v4

      # Copy .env file
      - name: Copy .env.test.local
        run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"
        working-directory: ${{env.working-directory}}

      # Install Dependencies
      - name: Install Dependencies
        working-directory: ${{env.working-directory}}
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      # Check composer packages
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: ./app/vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      
      # # Create Database
      # - name: Create Database
      #   run: |
      #     mkdir -p data
      #     touch data/database.sqlite

#      - name: Execute tests (Unit and Feature tests) via PHPUnit
#        env:
#          DATABASE_URL: sqlite:///%kernel.project_dir%/data/database.sqlite

      # https://github.com/phpstan/phpstan
      - name: Analyse PHP Code (PHPStan)
        run: vendor/bin/phpstan analyse
        working-directory: ${{env.working-directory}}

      # Analyse PHP code (rector)
      - name: Analyse PHP Code (Rector)
        run: vendor/bin/rector process --config rector.php --dry-run
        working-directory: ${{env.working-directory}}

      # Symfony
      - name: Check the Symfony console
        run: |
          php bin/console -V
          php bin/console about
        working-directory: ${{env.working-directory}}
  
      # Tests
      - name: Run the migrations
        working-directory: ${{env.working-directory}}
        run: |
            # php bin/console doctrine:database:drop --if-exists --force --env=test
            # php bin/console doctrine:database:create --if-not-exists --env=test
            # php bin/console doctrine:schema:update --env=test --force || echo "No migrations found or schema update failed"
            php bin/console doctrine:migrations:migrate --env=test || echo "No migrations found or migration failed"
            # php bin/console doctrine:fixtures:load --no-interaction
        env:
          DATABASE_URL: mysql://root:symfony@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/symfony
          
      - name: Run unit and functional tests
        working-directory: ${{env.working-directory}}
        run: |
          php bin/phpunit --stop-on-failure
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}

