name: Code analize (phpstan, rector, lint)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  analyze:
    runs-on: ubuntu-latest
    #concurrency:
    #  group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          
      - uses: actions/checkout@v4

      # Copy .env file
      - name: Copy .env.test.local
        run: php -r "file_exists('app/.env.test.local') || copy('app/.env.test', 'app/.env.test.local');"
      
#      # Check composer packages
#      - name: Cache Composer packages
#        id: composer-cache
#        uses: actions/cache@v3
#        with:
#          path: vendor
#          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
#          restore-keys: |
#            ${{ runner.os }}-php-

#      # Install Dependencies
#      - name: Install Dependencies
#        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      
#      # Create Database
#      - name: Create Database
#        run: |
#          mkdir -p data
#          touch data/database.sqlite

#      - name: Execute tests (Unit and Feature tests) via PHPUnit
#        env:
#          DATABASE_URL: sqlite:///%kernel.project_dir%/data/database.sqlite

      # https://github.com/phpstan/phpstan
#      - name: Analyse PHP Code (PHPStan)
#        run: vendor/bin/phpstan analyse
  
      # Symfony
#      - name: Check the Symfony console
#        run: |
#          php bin/console -V
#          php bin/console about
  
      # Tests
#      - name: Run the migrations
#        run: |
#          php bin/console doctrine:migrations:migrate --no-interaction
  
#      - name: Run unit and functional tests
#        run: |
#          php bin/phpunit --stop-on-failure
#        env:
#          DB_PORT: ${{ job.services.mysql.ports[3306] }}

