name: Code analize (phpstan, rector, lint)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  analyze:
    runs-on: ubuntu-latest
    #concurrency:
    #  group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          
      - uses: actions/checkout@v4
      
